<?php
/**
 * Set up changelog data.
 */
$data = array(
	'jumpstart-1' => array(
		'name'      => 'Jump Start v1',
		'slug'      => 'jumpstart-1',
		'url'       => __DIR__ . '/changelogs/jumpstart-1.txt',
		'buy'       => '',
		'support'   => '',
		'update'    => '',
		'docs'      => '',
	),
	'jumpstart' => array(
		'name'      => 'Jump Start',
		'slug'      => 'jumpstart',
		'url'       => 'http://demoblvd.com/shared-themes/jumpstart/changelog.txt',
		'buy'       => 'http://themeblvd.com/links/buy-jumpstart',
		'support'   => 'http://wpjumpstart.com/support',
		'update'    => 'http://docs.themeblvd.com/article/21-updates',
		'docs'      => 'http://docs.themeblvd.com',
	),
	'denali' => array(
		'name'      => 'Denali',
		'slug'      => 'denali',
		'url'       => 'http://demoblvd.com/shared-themes/denali/changelog.txt',
		'buy'       => 'http://themeblvd.com/links/buy-denali',
		'support'   => 'https://themeforest.net/item/denali-responsive-multipurpose-wordpress-theme/12679946/support?ref=themeblvd',
		'update'    => 'http://docs.themeblvd.com/article/20-updates-theme-forest',
		'docs'      => 'http://docs.themeblvd.com',
	),
	'gnar' => array(
		'name'      => 'Gnar',
		'slug'      => 'gnar',
		'url'       => 'http://demoblvd.com/shared-themes/gnar/changelog.txt',
		'buy'       => 'http://themeblvd.com/links/buy-gnar',
		'support'   => 'https://themeforest.net/item/gnar-action-adventure-travel-wordpress-theme/14674905/support?ref=themeblvd',
		'update'    => 'http://docs.themeblvd.com/article/20-updates-theme-forest',
		'docs'      => 'http://docs.themeblvd.com',
	),
	'akita' => array(
		'name'      => 'Akita',
		'slug'      => 'akita',
		'url'       => __DIR__ . '/changelogs/akita.txt',
		'buy'       => 'http://themeforest.net/item/akita-responsive-wordpress-theme/1530025?ref=themeblvd',
		'support'   => 'http://themeforest.net/item/akita-responsive-wordpress-theme/1530025/support?ref=themeblvd',
		'update'    => 'http://docs.themeblvd.com/article/20-updates-theme-forest',
		'docs'      => '',
	),
	'primetime' => array(
		'name'      => 'Prime Time',
		'slug'      => 'primetime',
		'url'       => __DIR__ . '/changelogs/primetime.txt',
		'buy'       => '',
		'support'   => '',
		'update'    => '',
		'docs'      => '',
	),
	'breakout' => array(
		'name'      => 'Breakout',
		'slug'      => 'breakout',
		'url'       => __DIR__ . '/changelogs/breakout.txt',
		'buy'       => '',
		'support'   => '',
		'update'    => '',
		'docs'      => '',
	),
	'arcadian' => array(
		'name'      => 'The Arcadian',
		'slug'      => 'arcadian',
		'url'       => __DIR__ . '/changelogs/arcadian.txt',
		'buy'       => 'http://themeforest.net/item/the-arcadian-responsive-wordpress-theme/1266406?ref=themeblvd',
		'support'   => 'http://themeforest.net/item/the-arcadian-responsive-wordpress-theme/1266406/support?ref=themeblvd',
		'update'    => 'http://docs.themeblvd.com/article/20-updates-theme-forest',
		'docs'      => '',
	),
	'swagger' => array(
		'name'      => 'Swagger',
		'slug'      => 'swagger',
		'url'       => __DIR__ . '/changelogs/swagger.txt',
		'buy'       => 'http://themeforest.net/item/swagger-responsive-wordpress-theme/930581?ref=themeblvd',
		'support'   => 'http://themeforest.net/item/swagger-responsive-wordpress-theme/930581/support?ref=themeblvd',
		'update'    => 'http://docs.themeblvd.com/article/20-updates-theme-forest',
		'docs'      => '',
	),
	'alyeska' => array(
		'name'      => 'Alyeska',
		'slug'      => 'alyeska',
		'url'       => __DIR__ . '/changelogs/alyeska.txt',
		'buy'       => 'http://themeforest.net/item/alyeska-responsive-wordpress-theme/164366?ref=themeblvd',
		'support'   => 'http://themeforest.net/item/alyeska-responsive-wordpress-theme/164366/support?ref=themeblvd',
		'update'    => 'http://docs.themeblvd.com/article/20-updates-theme-forest',
		'docs'      => '',
	),
	'commodore' => array(
		'name'      => 'Commodore',
		'slug'      => 'commodore',
		'url'       => __DIR__ . '/changelogs/commodore.txt',
		'buy'       => 'http://themeforest.net/item/commodore-responsive-wordpress-theme/111713?ref=themeblvd',
		'support'   => 'http://themeforest.net/item/commodore-responsive-wordpress-theme/111713/support?ref=themeblvd',
		'update'    => 'http://docs.themeblvd.com/article/20-updates-theme-forest',
		'docs'      => '',
	),
	'barelycorporate' => array(
		'name'      => 'Barely Corporate',
		'slug'      => 'barelycorporate',
		'url'       => __DIR__ . '/changelogs/barely-corporate.txt',
		'buy'       => 'http://themeforest.net/item/barely-corporate-responsive-wordpress-theme/93069?ref=themeblvd',
		'support'   => 'http://themeforest.net/item/barely-corporate-responsive-wordpress-theme/93069/support?ref=themeblvd',
		'update'    => 'http://docs.themeblvd.com/article/20-updates-theme-forest',
		'docs'      => '',
	),
);
